// Code generated by MockGen. DO NOT EDIT.
// Source: IRegister.go

// Package api is a generated GoMock package.
package api

import (
	context "context"
	models "ewallet-ums/internal/models"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockIRegisterService is a mock of IRegisterService interface.
type MockIRegisterService struct {
	ctrl     *gomock.Controller
	recorder *MockIRegisterServiceMockRecorder
}

// MockIRegisterServiceMockRecorder is the mock recorder for MockIRegisterService.
type MockIRegisterServiceMockRecorder struct {
	mock *MockIRegisterService
}

// NewMockIRegisterService creates a new mock instance.
func NewMockIRegisterService(ctrl *gomock.Controller) *MockIRegisterService {
	mock := &MockIRegisterService{ctrl: ctrl}
	mock.recorder = &MockIRegisterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRegisterService) EXPECT() *MockIRegisterServiceMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockIRegisterService) Register(ctx context.Context, request models.User) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, request)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockIRegisterServiceMockRecorder) Register(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIRegisterService)(nil).Register), ctx, request)
}

// MockIRegisterHandler is a mock of IRegisterHandler interface.
type MockIRegisterHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIRegisterHandlerMockRecorder
}

// MockIRegisterHandlerMockRecorder is the mock recorder for MockIRegisterHandler.
type MockIRegisterHandlerMockRecorder struct {
	mock *MockIRegisterHandler
}

// NewMockIRegisterHandler creates a new mock instance.
func NewMockIRegisterHandler(ctrl *gomock.Controller) *MockIRegisterHandler {
	mock := &MockIRegisterHandler{ctrl: ctrl}
	mock.recorder = &MockIRegisterHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRegisterHandler) EXPECT() *MockIRegisterHandlerMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockIRegisterHandler) Register(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", arg0)
}

// Register indicates an expected call of Register.
func (mr *MockIRegisterHandlerMockRecorder) Register(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIRegisterHandler)(nil).Register), arg0)
}
